/**
 * Below are the colors that are used in the app. The colors are defined in the light and dark mode.
 * There are many other ways to style your app. For example, [Nativewind](https://www.nativewind.dev/), [Tamagui](https://tamagui.dev/), [unistyles](https://reactnativeunistyles.vercel.app), etc.
 */

import { Platform } from 'react-native';

const designTokens = {
  light: {
    surface: '#f9f9f9',
    surfaceDim: '#dadada',
    surfaceBright: '#f9f9f9',
    surfaceContainerLowest: '#ffffff',
    surfaceContainerLow: '#f3f3f3',
    surfaceContainer: '#eeeeee',
    surfaceContainerHigh: '#e8e8e8',
    surfaceContainerHighest: '#e2e2e2',
    onSurface: '#1a1c1c',
    onSurfaceVariant: '#5b4039',
    inverseSurface: '#2f3131',
    inverseOnSurface: '#f1f1f1',
    outline: '#907067',
    outlineVariant: '#e4beb4',
    surfaceTint: '#b02f00',
    primary: '#b02f00',
    onPrimary: '#ffffff',
    primaryContainer: '#ff5722',
    onPrimaryContainer: '#541200',
    inversePrimary: '#ffb5a0',
    secondary: '#5f5e5e',
    onSecondary: '#ffffff',
    secondaryContainer: '#e2dfde',
    onSecondaryContainer: '#636262',
    tertiary: '#466270',
    onTertiary: '#ffffff',
    tertiaryContainer: '#7895a4',
    onTertiaryContainer: '#0e2d39',
    error: '#ba1a1a',
    onError: '#ffffff',
    errorContainer: '#ffdad6',
    onErrorContainer: '#93000a',
    primaryFixed: '#ffdbd1',
    primaryFixedDim: '#ffb5a0',
    onPrimaryFixed: '#3b0900',
    onPrimaryFixedVariant: '#862200',
    secondaryFixed: '#e5e2e1',
    secondaryFixedDim: '#c8c6c5',
    onSecondaryFixed: '#1c1b1b',
    onSecondaryFixedVariant: '#474746',
    tertiaryFixed: '#c9e7f7',
    tertiaryFixedDim: '#adcbda',
    onTertiaryFixed: '#001f2a',
    onTertiaryFixedVariant: '#2e4b57',
    background: '#f9f9f9',
    onBackground: '#1a1c1c',
    surfaceVariant: '#e2e2e2',
  },
  dark: {
    surface: '#121212',
    surfaceDim: '#0f1112',
    surfaceBright: '#1d2123',
    surfaceContainerLowest: '#0b0d0e',
    surfaceContainerLow: '#171a1c',
    surfaceContainer: '#1d2022',
    surfaceContainerHigh: '#282c2f',
    surfaceContainerHighest: '#33383b',
    onSurface: '#f2f2f2',
    onSurfaceVariant: '#d6c4bd',
    inverseSurface: '#f2f2f2',
    inverseOnSurface: '#2f3131',
    outline: '#9c857e',
    outlineVariant: '#4f3c36',
    surfaceTint: '#ffb5a0',
    primary: '#ffb5a0',
    onPrimary: '#3b0900',
    primaryContainer: '#862200',
    onPrimaryContainer: '#ffdbd1',
    inversePrimary: '#b02f00',
    secondary: '#c8c6c5',
    onSecondary: '#2f2f2f',
    secondaryContainer: '#474746',
    onSecondaryContainer: '#e5e2e1',
    tertiary: '#adcbda',
    onTertiary: '#0e2d39',
    tertiaryContainer: '#2e4b57',
    onTertiaryContainer: '#c9e7f7',
    error: '#ffb4ab',
    onError: '#690005',
    errorContainer: '#93000a',
    onErrorContainer: '#ffdad6',
    primaryFixed: '#ffdbd1',
    primaryFixedDim: '#ffb5a0',
    onPrimaryFixed: '#3b0900',
    onPrimaryFixedVariant: '#862200',
    secondaryFixed: '#e5e2e1',
    secondaryFixedDim: '#c8c6c5',
    onSecondaryFixed: '#1c1b1b',
    onSecondaryFixedVariant: '#474746',
    tertiaryFixed: '#c9e7f7',
    tertiaryFixedDim: '#adcbda',
    onTertiaryFixed: '#001f2a',
    onTertiaryFixedVariant: '#2e4b57',
    background: '#121212',
    onBackground: '#f2f2f2',
    surfaceVariant: '#2f3131',
  },
};

const lightColors = {
  ...designTokens.light,
  text: designTokens.light.onSurface,
  background: designTokens.light.background,
  tint: designTokens.light.primary,
  icon: designTokens.light.onSurfaceVariant,
  tabIconDefault: designTokens.light.onSurfaceVariant,
  tabIconSelected: designTokens.light.primary,
};

const darkColors = {
  ...designTokens.dark,
  text: designTokens.dark.onSurface,
  background: designTokens.dark.background,
  tint: designTokens.dark.primary,
  icon: designTokens.dark.onSurfaceVariant,
  tabIconDefault: designTokens.dark.onSurfaceVariant,
  tabIconSelected: designTokens.dark.primary,
};

export const Colors = {
  light: lightColors,
  dark: darkColors,
};

export const Fonts = Platform.select({
  ios: {
    /** iOS `UIFontDescriptorSystemDesignDefault` */
    sans: 'system-ui',
    /** iOS `UIFontDescriptorSystemDesignSerif` */
    serif: 'ui-serif',
    /** iOS `UIFontDescriptorSystemDesignRounded` */
    rounded: 'ui-rounded',
    /** iOS `UIFontDescriptorSystemDesignMonospaced` */
    mono: 'ui-monospace',
  },
  default: {
    sans: 'normal',
    serif: 'serif',
    rounded: 'normal',
    mono: 'monospace',
  },
  web: {
    sans: "system-ui, -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Helvetica, Arial, sans-serif",
    serif: "Georgia, 'Times New Roman', serif",
    rounded: "'SF Pro Rounded', 'Hiragino Maru Gothic ProN', Meiryo, 'MS PGothic', sans-serif",
    mono: "SFMono-Regular, Menlo, Monaco, Consolas, 'Liberation Mono', 'Courier New', monospace",
  },
});
